---
title: "SIR Model Example"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(deSolve)
```

**Credit:** This example is built on (and closely follows) the example presented [here](http://rstudio-pubs-static.s3.amazonaws.com/6852_c59c5a2e8ea3456abbeb017185de603e.html) by Dr. Aidan Findlater

## Set up: define parameters

```{r}
### Specify parameters

## Proportion in each compartment: Susceptible 0.999999, Infected 0.000001, Recovered 0 (these are directly from the example linked above)
init <- c(S = 1-1e-6, I = 1e-6, R = 0.0)

## beta: infection parameter; gamma: recovery parameter
parameters <- c(beta = 2.316, gamma = 0.261)

## Time frame
times      <- seq(0, 100, by = 0.5)
```

## Create the function with the differential equations:

```{r}
## Build the function with all 
sir <- function(time, init, parameters) {

  with(as.list(c(init, parameters)), {

    dS <- -beta * S * I
    dI <-  beta * S * I - gamma * I
    dR <-  gamma * I
    
    return(list(c(dS, dI, dR)))
  })
}
```

## Approximate the solution using `deSolve::ode()`:
```{r}
## Solve using `deSolve::ode()`
approximation <- ode(y = init, times = times, func = sir, parms = parameters)
```

## Make it something we can plot:
```{r}
## Get output into a data frame
approx_df <- as.data.frame(approximation)

## Pivot longer so R will do the work for us: 
approx_long <- approx_df %>% 
  pivot_longer(cols = S:R, names_to = "population", values_to = "proportion")

```

## Plot the output with ggplot:
```{r}
ggplot(data = approx_long, aes(x = time, y = proportion)) +
  geom_line(aes(color = population))
```

## End
